services:
  db:
    image: postgres:15
    container_name: cleanbooker_db
    restart: always
    environment:
      POSTGRES_USER: cleanbooker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cleanbooker_db
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cleanbooker -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    # command: postgres -c listen_addresses='*'
    # logging:
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  server:
    container_name: cleanbooker_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true # Keeps the container running for debugging
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env
    networks:
      - prisma-network
  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /app
    volumes:
      - .:/app
    command: npx prisma studio --schema=./server/prisma/schema.prisma --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - ./server/.env
    networks:
      - prisma-network
    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_started

networks:
  prisma-network:
    name: prisma-network
